---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx

- name: Deploy Jenkins vhost config
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/sites-available/jenkins
    mode: '0644'
  notify: Reload Nginx

- name: Enable Jenkins vhost
  file:
    src: /etc/nginx/sites-available/jenkins
    dest: /etc/nginx/sites-enabled/jenkins
    state: link
  notify: Reload Nginx

- name: Test Nginx configuration
  command: nginx -t
  changed_when: false

- name: Enable and start Nginx
  systemd:
    name: nginx
    enabled: true
    state: started
